export const FRAME_BACKGROUND_ITEMS = {
  COLOR: "COLOR",
  TRANSPARENT: "TRANSPARENT",
  BACKGROUND: "BACKGROUND",
};
export const FRAME_TYPE = {
  MAC_FRAME: {
    label: "Mac Browser",
    ratio: "2560 x 200",
    img: "url",
    height: "45.214%",
    width: "60%",
    tags: ["All", "Desktops"],
    CSSID: {
      mac_frame_window: {
        borderRadius: [12, 12, 12, 12],
      },
      mac_frame_winhead: {
        borderRadius: [12, 12, 0, 0],
      },
      mac_frame_button_close: {
        width: [12],
        marginLeft: [6],
        borderWidth: [0.5],
      },
      mac_frame_button_min: {
        width: [12],
        marginLeft: [6],
        borderWidth: [0.5],
      },
      mac_frame_button_max: {
        width: [12],
        marginLeft: [6],
        borderWidth: [0.5],
      },
      mac_frame_dropShadow: {
        borderRadius: [0, 0, 12, 12],
        boxShadow: [9, 2, 25],
      },
      mac_frame_winbody: {
        borderRadius: [0, 0, 12, 12],
      },
      transparent_container: {
        transform: [12, 12],
      },
      image_container: {},
    },
  },
  APPLE_IPHONE_14: {
    label: "Apple Iphone 14",
    ratio: "2560 x 200",
    img: "url(/icons/iphone15.png)",
    height: "54%",
    width: "30%",
    tags: ["All", "Phones"],
    drop_shadow: {
      width: "78%",
      height: "96%",
      borderRadius: "6px",
    },
    CSSID: {
      iphone14_dropShadow: {
        boxShadow: [9, 2, 25],
      },
      transparent_container: {
        transform: [12, 12],
      },
      image_container: {},
    },
  },
  MACBOOK_PRO_16: {
    label: "Macbook Pro 16",
    ratio: "2560 x 200",
    img: "url(/icons/macbook-pro-16.png)",
    height: "40%",
    width: "60%",
    tags: ["All", "Laptop"],
    drop_shadow: {
      width: "80%",
      height: "79%",
      position: "absolute",
    },
  },
  MACBOOK_AIR_M2: {
    label: "Macbook Air M2",
    ratio: "2560 x 200",
    img: "url(/icons/macbook-air-m2.png)",
    height: "40%",
    width: "60%",
    tags: ["All", "Laptop"],
    drop_shadow: {
      width: "80%",
      height: "85%",
      position: "absolute",
    },
  },
  APPLE_IMAC: {
    label: "Apple imac",
    ratio: "2560 x 200",
    img: "url",
    tags: ["All", "Phones"],
  },
  IPHONE_15_BLUE: {
    label: "Iphone 15 Blue",
    ratio: "2560 x 200",
    img: "url(/icons/iphone-15-dark-blue.png)",
    tags: ["All", "Phones"],
    height: "54%",
    width: "30%",
    drop_shadow: {
      width: "78%",
      height: "92%",
      borderRadius: "10px",
    },
  },
  IPHONE_15_BLACK: {
    label: "Iphone 15 Black",
    ratio: "2560 x 200",
    img: "url(/icons/iphone-15-black.png)",
    tags: ["All", "Phones"],
    height: "54%",
    width: "30%",
    drop_shadow: {
      width: "78%",
      height: "92%",
      borderRadius: "10px",
    },
  },
  APPLE_ULTRA_WATCH: {
    label: "Apple Ultra Watch",
    ratio: "2560 x 200",
    img: "url(/icons/apple-watch-ultra.png)",
    height: "54%",
    width: "30%",
    tags: ["All", "Wearables"],
    drop_shadow: {
      width: "74%",
      height: "48%",
    },
  },
  PRO_DISPLAY_XDR: {
    label: "Apple XDR display",
    ratio: "2560 x 200",
    img: "url(/icons/pro-display-xdr.png)",
    height: "40%",
    width: "60%",
    tags: ["All", "Desktops"],
    drop_shadow: {
      width: "86%",
      height: "72%",
      position: "absolute",
      top: "7px",
    },
  },
  IMAC_24: {
    label: "Apple IMAC 24",
    ratio: "2560 x 200",
    img: "url(/icons/imac24-silver.png)",
    height: "40%",
    width: "60%",
    tags: ["All", "Desktops"],
    drop_shadow: {
      width: "73%",
      height: "72%",
      position: "absolute",
      top: "7px",
    },
  },
  IPAD_MINI: {
    label: "Apple Ipad Mini",
    ratio: "2560 x 200",
    img: "url(/icons/ipad-mini.png)",
    height: "40%",
    width: "60%",
    tags: ["All", "Tablets"],
    drop_shadow: {
      width: "82%",
      height: "85%",
      position: "absolute",
      borderRadius: "10px",
    },
  },
  IPAD_PRO_13: {
    label: "Ipad Pro 13",
    ratio: "2560 x 200",
    img: "url(/icons/ipad-pro-13.png)",
    height: "40%",
    width: "60%",
    tags: ["All", "Tablets"],
    drop_shadow: {
      width: "92%",
      height: "95%",
      position: "absolute",
      borderRadius: "10px",
    },
  },
  IPAD_PRO_11: {
    label: "Ipad Pro 11",
    ratio: "2560 x 200",
    img: "url(/icons/ipad-pro-11.png)",
    height: "40%",
    width: "60%",
    tags: ["All", "Tablets"],
    drop_shadow: {
      width: "92%",
      height: "95%",
      position: "absolute",
      borderRadius: "10px",
    },
  },
};
